config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :events do
    resources :subscriptions
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_user_context

  def store_user_context
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_info
    { id: @current_user.id, login: @current_user.login, role: @current_user.role }
  end

  def is_admin?
    @current_user && @current_user.role == 'admin'
  end

  private

  def logged_in?
    session[:user_id].present?
  end

  helper_method :logged_in?, :user_info, :is_admin?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.comments.create(
      body: comment_params[:body],
      commenter: user_info[:login]
    )
    redirect_to event_path(@event)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    redirect_to events_path if !is_admin?
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    redirect_to events_path if !is_admin?
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    notice = 'You have no permission.'
    if is_admin?
      @event.destroy
      notice = 'Event was successfully destroyed.'
    end
    respond_to do |format|
      format.html { redirect_to events_url, notice: notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :place, :date, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(login: params[:login])
    if user && user.password == params[:password]
      session[:user_id] = user.id
    else
      flash.now.alert = 'Email or password is invalid'
    end
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.subscriptions.create(
      user_id: user_info[:id]
    )
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @subscription = @event.subscriptions.find(params[:id])
    @subscription.destroy
    redirect_to event_path(@event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_new.html.erb
<%= form_for([@event, @event.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :event_place %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.place %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <% if is_admin? %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path if is_admin? %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <% if @current_user && @current_user.role == 'user' %>
    <%= render 'subscriptions/form' %>
  <% end %>
</p>

<h2>Comments</h2>
<%= render @event.comments %>

<% if @current_user %>
<h2>Add a comment:</h2>
<%= render 'comments/new' %>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) if is_admin? %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework5_v.11</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <div id="user_header">
        <% if logged_in? %>
          <%= "Logged in as: #{user_info[:login]}" %>
          <%= link_to 'Logout', logout_path %>
        <% else %>
          <%= render 'sessions/new' %>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<% if @event.subscriptions.find{|s| s.user_id == user_info[:id]} %>
  <p> you are subscribed </p>
  <%= link_to 'Unsubscribe', [@event, @event.subscriptions.find{|s| s.user_id == user_info[:id]}],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<% else %>
  <%= form_for([@event, @event.subscriptions.build]) do |f| %>
    <p><%= f.submit %></p>
  <% end %>
<% end %>